// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.spotlight.track;


public class AddActionResponse {
    protected java.lang.String addActionResult;
    
    public AddActionResponse() {
    }
    
    public AddActionResponse(java.lang.String addActionResult) {
        this.addActionResult = addActionResult;
    }
    
    public java.lang.String getAddActionResult() {
        return addActionResult;
    }
    
    public void setAddActionResult(java.lang.String addActionResult) {
        this.addActionResult = addActionResult;
    }
}
